version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_cpem_68.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  redis:
    image: redis
    ports:
      - "6379:6379"

  pirra_1:
    build: .
    container_name: pirra_1
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=swettcute.pirra.local
      - DJANGO_DATABASE=swettcute
      - DJANGO_DATABASE_USER=swettcute
      - DJANGO_DATABASE_PASSWORD=${SWETTCUTE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_2:
    build: .
    container_name: pirra_2
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=treeluches.pirra.local
      - DJANGO_DATABASE=treeluches
      - DJANGO_DATABASE_USER=treeluches
      - DJANGO_DATABASE_PASSWORD=${TREELUCHES_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_3:
    build: .
    container_name: pirra_3
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=zonacell.pirra.local
      - DJANGO_DATABASE=zonacell
      - DJANGO_DATABASE_USER=zonacell
      - DJANGO_DATABASE_PASSWORD=${ZONACELL_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_4:
    build: .
    container_name: pirra_4
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=akeakamai.pirra.local
      - DJANGO_DATABASE=akeakamai
      - DJANGO_DATABASE_USER=akeakamai
      - DJANGO_DATABASE_PASSWORD=${AKEAKAMAI_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_5:
    build: .
    container_name: pirra_5
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=reyhamburguesa.pirra.local
      - DJANGO_DATABASE=reyhamburguesa
      - DJANGO_DATABASE_USER=reyhamburguesa
      - DJANGO_DATABASE_PASSWORD=${REYHAMBURGUESA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m
