version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx_cpem_17.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  redis:
    image: redis
    ports:
      - "6379:6379"

  pirra_1:
    build: .
    container_name: pirra_1
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=dnb.pirra.local
      - DJANGO_DATABASE=dnb
      - DJANGO_DATABASE_USER=dnb
      - DJANGO_DATABASE_PASSWORD=${DNB_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_2:
    build: .
    container_name: pirra_2
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=sportvla.pirra.local
      - DJANGO_DATABASE=sportvla
      - DJANGO_DATABASE_USER=sportvla
      - DJANGO_DATABASE_PASSWORD=${SPORTVLA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_3:
    build: .
    container_name: pirra_3
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=daiwel.pirra.local
      - DJANGO_DATABASE=daiwel
      - DJANGO_DATABASE_USER=daiwel
      - DJANGO_DATABASE_PASSWORD=${DAIWEL_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_4:
    build: .
    container_name: pirra_4
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=tiendadedeportes.pirra.local
      - DJANGO_DATABASE=tiendadedeportes
      - DJANGO_DATABASE_USER=tiendadedeportes
      - DJANGO_DATABASE_PASSWORD=${TIENDADEDEPORTES_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_5:
    build: .
    container_name: pirra_5
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=peperairhips.pirra.local
      - DJANGO_DATABASE=peperairhips
      - DJANGO_DATABASE_USER=peperairhips
      - DJANGO_DATABASE_PASSWORD=${PEPERAIRHIPS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_6:
    build: .
    container_name: pirra_6
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=fandomshop.pirra.local
      - DJANGO_DATABASE=fandomshop
      - DJANGO_DATABASE_USER=fandomshop
      - DJANGO_DATABASE_PASSWORD=${FANDOMSHOP_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_7:
    build: .
    container_name: pirra_7
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=narniashop.pirra.local
      - DJANGO_DATABASE=narniashop
      - DJANGO_DATABASE_USER=narniashop
      - DJANGO_DATABASE_PASSWORD=${NARNIASHOP_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_8:
    build: .
    container_name: pirra_8
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=cpem17.pirra.local
      - DJANGO_DATABASE=cpem17
      - DJANGO_DATABASE_USER=cpem17
      - DJANGO_DATABASE_PASSWORD=${CPEM17_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_9:
    build: .
    container_name: pirra_9
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=cpem68.pirra.local
      - DJANGO_DATABASE=cpem68
      - DJANGO_DATABASE_USER=cpem68
      - DJANGO_DATABASE_PASSWORD=${CPEM68_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m
