version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  redis:
    image: redis
    ports:
      - "6379:6379"

  pirra_1:
    build: .
    container_name: pirra_1
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g1.pirra.local
      - DJANGO_DATABASE=g1
    expose:
      - "8080"

  pirra_2:
    build: .
    container_name: pirra_2
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g2.pirra.local
      - DJANGO_DATABASE=g2
    expose:
      - "8080"