version: '3'

volumes:
  static:
    driver: local
  db-data:

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: pirra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  redis:
    image: redis
    ports:
      - "6379:6379"

  django:
    build: .
    restart: always
    container_name: django
    environment:
      - DJANGO_DATABASE=pirra
      - DJANGO_DATABASE_USER=postgres
      - DJANGO_DATABASE_PASSWORD=postgres
      - USE_DOCKER=yes
    expose:
      - "5000"
    volumes:
      - .:/usr/src/app
      - static:/usr/src/app/static

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
