version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  redis:
    image: redis
    ports:
      - "6379:6379"

  pirra_1:
    build: .
    container_name: pirra_1
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g1.pirra.local
      - DJANGO_DATABASE=g1
      - DJANGO_DATABASE_USER=g1
      - DJANGO_DATABASE_PASSWORD=${G1_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_2:
    build: .
    container_name: pirra_2
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g2.pirra.local
      - DJANGO_DATABASE=g2
      - DJANGO_DATABASE_USER=g2
      - DJANGO_DATABASE_PASSWORD=${G2_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_3:
    build: .
    container_name: pirra_3
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=essencial.pirra.local
      - DJANGO_DATABASE=essencial
      - DJANGO_DATABASE_USER=essencial
      - DJANGO_DATABASE_PASSWORD=${ESSENCIAL_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_4:
    build: .
    container_name: pirra_4
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=tecnoshop.pirra.local
      - DJANGO_DATABASE=tecnoshop
      - DJANGO_DATABASE_USER=tecnoshop
      - DJANGO_DATABASE_PASSWORD=${TECNOSHOP_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_5:
    build: .
    container_name: pirra_5
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=papelandia.pirra.local
      - DJANGO_DATABASE=papelandia
      - DJANGO_DATABASE_USER=papelandia
      - DJANGO_DATABASE_PASSWORD=${PAPELANDIA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_6:
    build: .
    container_name: pirra_6
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=burita.pirra.local
      - DJANGO_DATABASE=burita
      - DJANGO_DATABASE_USER=burita
      - DJANGO_DATABASE_PASSWORD=${BURITA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_7:
    build: .
    container_name: pirra_7
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=electrodomesticos.pirra.local
      - DJANGO_DATABASE=electrodomesticos
      - DJANGO_DATABASE_USER=electrodomesticos
      - DJANGO_DATABASE_PASSWORD=${ELECTRODOMESTICOS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_8:
    build: .
    container_name: pirra_8
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=lahumildad.pirra.local
      - DJANGO_DATABASE=lahumildad
      - DJANGO_DATABASE_USER=lahumildad
      - DJANGO_DATABASE_PASSWORD=${LAHUMILDAD_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_9:
    build: .
    container_name: pirra_9
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=paraelhogar.pirra.local
      - DJANGO_DATABASE=paraelhogar
      - DJANGO_DATABASE_USER=paraelhogar
      - DJANGO_DATABASE_PASSWORD=${PARAELHOGAR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_10:
    build: .
    container_name: pirra_10
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=computadoras.pirra.local
      - DJANGO_DATABASE=computadoras
      - DJANGO_DATABASE_USER=computadoras
      - DJANGO_DATABASE_PASSWORD=${COMPUTADORAS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_11:
    build: .
    container_name: pirra_11
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=maktruckking.pirra.local
      - DJANGO_DATABASE=maktruckking
      - DJANGO_DATABASE_USER=maktruckking
      - DJANGO_DATABASE_PASSWORD=${MAKTRUCKKING_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_12:
    build: .
    container_name: pirra_12
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=thelastbookstore.pirra.local
      - DJANGO_DATABASE=thelastbookstore
      - DJANGO_DATABASE_USER=thelastbookstore
      - DJANGO_DATABASE_PASSWORD=${THELASTBOOKSTORE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_13:
    build: .
    container_name: pirra_13
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=cirio.pirra.local
      - DJANGO_DATABASE=cirio
      - DJANGO_DATABASE_USER=cirio
      - DJANGO_DATABASE_PASSWORD=${CIRIO_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_14:
    build: .
    container_name: pirra_14
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=tecssirve.pirra.local
      - DJANGO_DATABASE=tecssirve
      - DJANGO_DATABASE_USER=tecssirve
      - DJANGO_DATABASE_PASSWORD=${TECSSIRVE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_15:
    build: .
    container_name: pirra_15
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=argentinaturismo.pirra.local
      - DJANGO_DATABASE=argentinaturismo
      - DJANGO_DATABASE_USER=argentinaturismo
      - DJANGO_DATABASE_PASSWORD=${ARGENTINATURISMO_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_16:
    build: .
    container_name: pirra_16
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=vendemostodo.pirra.local
      - DJANGO_DATABASE=vendemostodo
      - DJANGO_DATABASE_USER=vendemostodo
      - DJANGO_DATABASE_PASSWORD=${VENDEMOSTODO_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_17:
    build: .
    container_name: pirra_17
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=aerocondor.pirra.local
      - DJANGO_DATABASE=aerocondor
      - DJANGO_DATABASE_USER=aerocondor
      - DJANGO_DATABASE_PASSWORD=${AEROCONDOR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_18:
    build: .
    container_name: pirra_18
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=materos.pirra.local
      - DJANGO_DATABASE=materos
      - DJANGO_DATABASE_USER=materos
      - DJANGO_DATABASE_PASSWORD=${MATEROS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_19:
    build: .
    container_name: pirra_19
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=lhd.pirra.local
      - DJANGO_DATABASE=lhd
      - DJANGO_DATABASE_USER=lhd
      - DJANGO_DATABASE_PASSWORD=${LHD_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_20:
    build: .
    container_name: pirra_20
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=mollange.pirra.local
      - DJANGO_DATABASE=mollange
      - DJANGO_DATABASE_USER=mollange
      - DJANGO_DATABASE_PASSWORD=${MOLLANGE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_21:
    build: .
    container_name: pirra_21
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=mediasocre.pirra.local
      - DJANGO_DATABASE=mediasocre
      - DJANGO_DATABASE_USER=mediasocre
      - DJANGO_DATABASE_PASSWORD=${MEDIASOCRE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_22:
    build: .
    container_name: pirra_22
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=sancho.pirra.local
      - DJANGO_DATABASE=sancho
      - DJANGO_DATABASE_USER=sancho
      - DJANGO_DATABASE_PASSWORD=${SANCHO_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_23:
    build: .
    container_name: pirra_23
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=mypets.pirra.local
      - DJANGO_DATABASE=mypets
      - DJANGO_DATABASE_USER=mypets
      - DJANGO_DATABASE_PASSWORD=${MYPETS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_24:
    build: .
    container_name: pirra_24
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=elpepe.pirra.local
      - DJANGO_DATABASE=elpepe
      - DJANGO_DATABASE_USER=elpepe
      - DJANGO_DATABASE_PASSWORD=${ELPEPE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_25:
    build: .
    container_name: pirra_25
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=harrisandcompany.pirra.local
      - DJANGO_DATABASE=harrisandcompany
      - DJANGO_DATABASE_USER=harrisandcompany
      - DJANGO_DATABASE_PASSWORD=${HARRISANDCOMPANY_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_26:
    build: .
    container_name: pirra_26
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=proxel.pirra.local
      - DJANGO_DATABASE=proxel
      - DJANGO_DATABASE_USER=proxel
      - DJANGO_DATABASE_PASSWORD=${PROXEL_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_27:
    build: .
    container_name: pirra_27
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=perfumeriakaori.pirra.local
      - DJANGO_DATABASE=perfumeriakaori
      - DJANGO_DATABASE_USER=perfumeriakaori
      - DJANGO_DATABASE_PASSWORD=${PERFUMERIAKAORI_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_28:
    build: .
    container_name: pirra_28
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=musicstar.pirra.local
      - DJANGO_DATABASE=musicstar
      - DJANGO_DATABASE_USER=musicstar
      - DJANGO_DATABASE_PASSWORD=${MUSICSTAR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_29:
    build: .
    container_name: pirra_29
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=booklook.pirra.local
      - DJANGO_DATABASE=booklook
      - DJANGO_DATABASE_USER=booklook
      - DJANGO_DATABASE_PASSWORD=${BOOKLOOK_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_30:
    build: .
    container_name: pirra_30
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=indumentariaking.pirra.local
      - DJANGO_DATABASE=indumentariaking
      - DJANGO_DATABASE_USER=indumentariaking
      - DJANGO_DATABASE_PASSWORD=${INDUMENTARIAKING_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_31:
    build: .
    container_name: pirra_31
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=culturavintage.pirra.local
      - DJANGO_DATABASE=culturavintage
      - DJANGO_DATABASE_USER=culturavintage
      - DJANGO_DATABASE_PASSWORD=${CULTURAVINTAGE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_32:
    build: .
    container_name: pirra_32
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=ciberneticos.pirra.local
      - DJANGO_DATABASE=ciberneticos
      - DJANGO_DATABASE_USER=ciberneticos
      - DJANGO_DATABASE_PASSWORD=${CIBERNETICOS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_33:
    build: .
    container_name: pirra_33
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=fullsport.pirra.local
      - DJANGO_DATABASE=fullsport
      - DJANGO_DATABASE_USER=fullsport
      - DJANGO_DATABASE_PASSWORD=${FULLSPORT_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_34:
    build: .
    container_name: pirra_34
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=sportvla.pirra.local
      - DJANGO_DATABASE=sportvla
      - DJANGO_DATABASE_USER=sportvla
      - DJANGO_DATABASE_PASSWORD=${SPORTVLA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_35:
    build: .
    container_name: pirra_35
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=nestitor.pirra.local
      - DJANGO_DATABASE=nestitor
      - DJANGO_DATABASE_USER=nestitor
      - DJANGO_DATABASE_PASSWORD=${NESTITOR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_36:
    build: .
    container_name: pirra_36
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=autosportangostura.pirra.local
      - DJANGO_DATABASE=autosportangostura
      - DJANGO_DATABASE_USER=autosportangostura
      - DJANGO_DATABASE_PASSWORD=${AUTOSPORTANGOSTURA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_37:
    build: .
    container_name: pirra_37
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=mueblesindustriaargentina.pirra.local
      - DJANGO_DATABASE=mueblesindustriaargentina
      - DJANGO_DATABASE_USER=mueblesindustriaargentina
      - DJANGO_DATABASE_PASSWORD=${MUEBLESINDUSTRIAARGENTINA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_38:
    build: .
    container_name: pirra_38
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=lahuella.pirra.local
      - DJANGO_DATABASE=lahuella
      - DJANGO_DATABASE_USER=lahuella
      - DJANGO_DATABASE_PASSWORD=${LAHUELLA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_39:
    build: .
    container_name: pirra_39
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=energivla.pirra.local
      - DJANGO_DATABASE=energivla
      - DJANGO_DATABASE_USER=energivla
      - DJANGO_DATABASE_PASSWORD=${ENERGIVLA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_40:
    build: .
    container_name: pirra_40
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=lapicessa.pirra.local
      - DJANGO_DATABASE=lapicessa
      - DJANGO_DATABASE_USER=lapicessa
      - DJANGO_DATABASE_PASSWORD=${LAPICESSA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_41:
    build: .
    container_name: pirra_41
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=electrodelsur.pirra.local
      - DJANGO_DATABASE=electrodelsur
      - DJANGO_DATABASE_USER=electrodelsur
      - DJANGO_DATABASE_PASSWORD=${ELECTRODELSUR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_42:
    build: .
    container_name: pirra_42
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=veralopez.pirra.local
      - DJANGO_DATABASE=veralopez
      - DJANGO_DATABASE_USER=veralopez
      - DJANGO_DATABASE_PASSWORD=${VERALOPEZ_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_43:
    build: .
    container_name: pirra_43
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=tupana.pirra.local
      - DJANGO_DATABASE=tupana
      - DJANGO_DATABASE_USER=tupana
      - DJANGO_DATABASE_PASSWORD=${TUPANA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_44:
    build: .
    container_name: pirra_44
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=elpalaciodelosespejos.pirra.local
      - DJANGO_DATABASE=elpalaciodelosespejos
      - DJANGO_DATABASE_USER=elpalaciodelosespejos
      - DJANGO_DATABASE_PASSWORD=${ELPALACIODELOSESPEJOS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_45:
    build: .
    container_name: pirra_45
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=goodhouse.pirra.local
      - DJANGO_DATABASE=goodhouse
      - DJANGO_DATABASE_USER=goodhouse
      - DJANGO_DATABASE_PASSWORD=${GOODHOUSE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_46:
    build: .
    container_name: pirra_46
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=gorrasfacheras.pirra.local
      - DJANGO_DATABASE=gorrasfacheras
      - DJANGO_DATABASE_USER=gorrasfacheras
      - DJANGO_DATABASE_PASSWORD=${GORRASFACHERAS_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_47:
    build: .
    container_name: pirra_47
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=intentar.pirra.local
      - DJANGO_DATABASE=intentar
      - DJANGO_DATABASE_USER=intentar
      - DJANGO_DATABASE_PASSWORD=${INTENTAR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_48:
    build: .
    container_name: pirra_48
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=losartesanosdelsur.pirra.local
      - DJANGO_DATABASE=losartesanosdelsur
      - DJANGO_DATABASE_USER=losartesanosdelsur
      - DJANGO_DATABASE_PASSWORD=${LOSARTESANOSDELSUR_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_49:
    build: .
    container_name: pirra_49
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=karensindumentaria.pirra.local
      - DJANGO_DATABASE=karensindumentaria
      - DJANGO_DATABASE_USER=karensindumentaria
      - DJANGO_DATABASE_PASSWORD=${KARENSINDUMENTARIA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_50:
    build: .
    container_name: pirra_50
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=fresh.pirra.local
      - DJANGO_DATABASE=fresh
      - DJANGO_DATABASE_USER=fresh
      - DJANGO_DATABASE_PASSWORD=${FRESH_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_51:
    build: .
    container_name: pirra_51
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=perfumeriadiamont.pirra.local
      - DJANGO_DATABASE=perfumeriadiamont
      - DJANGO_DATABASE_USER=perfumeriadiamont
      - DJANGO_DATABASE_PASSWORD=${PERFUMERIADIAMONT_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_52:
    build: .
    container_name: pirra_52
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=bonnevoyage.pirra.local
      - DJANGO_DATABASE=bonnevoyage
      - DJANGO_DATABASE_USER=bonnevoyage
      - DJANGO_DATABASE_PASSWORD=${BONNEVOYAGE_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_53:
    build: .
    container_name: pirra_53
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g1segundoa.pirra.local
      - DJANGO_DATABASE=g1segundoa
      - DJANGO_DATABASE_USER=g1segundoa
      - DJANGO_DATABASE_PASSWORD=${G1SEGUNDOA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_54:
    build: .
    container_name: pirra_54
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g2segundoa.pirra.local
      - DJANGO_DATABASE=g2segundoa
      - DJANGO_DATABASE_USER=g2segundoa
      - DJANGO_DATABASE_PASSWORD=${G2SEGUNDOA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_55:
    build: .
    container_name: pirra_55
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g3segundoa.pirra.local
      - DJANGO_DATABASE=g3segundoa
      - DJANGO_DATABASE_USER=g3segundoa
      - DJANGO_DATABASE_PASSWORD=${G3SEGUNDOA_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_56:
    build: .
    container_name: pirra_56
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g1segundod.pirra.local
      - DJANGO_DATABASE=g1segundod
      - DJANGO_DATABASE_USER=g1segundod
      - DJANGO_DATABASE_PASSWORD=${G1SEGUNDOD_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m

  pirra_57:
    build: .
    container_name: pirra_57
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL=g2segundod.pirra.local
      - DJANGO_DATABASE=g2segundod
      - DJANGO_DATABASE_USER=g2segundod
      - DJANGO_DATABASE_PASSWORD=${G2SEGUNDOD_DB_PASSWORD}
    expose:
      - "8080"
    mem_limit: 160m
