# Generated by Django 2.2.4 on 2019-08-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlicuotaIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
                ('porc', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('ws_afip', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionIIBB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['id_afip'],
            },
        ),
        migrations.CreateModel(
            name='CondicionVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Incoterms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
                ('simbolo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.CharField(max_length=10)),
                ('campo', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('cuit', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=30)),
                ('imp_ganancias', models.CharField(max_length=2)),
                ('imp_iva', models.CharField(max_length=2)),
                ('monotributo', models.CharField(max_length=2)),
                ('integrante_soc', models.CharField(max_length=1)),
                ('empleador', models.CharField(max_length=1)),
                ('actividad_monotributo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PaisDestino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
                ('cuit', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=256, null=True)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
                ('letra', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobanteAlicuotaIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('alicuota_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.AlicuotaIva')),
                ('tipo_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.TipoComprobante')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionOpcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.Opcional')),
            ],
        ),
        migrations.AddField(
            model_name='opcional',
            name='resolucion_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.ResolucionGeneral'),
        ),
    ]
