# Generated by Django 2.2.4 on 2019-08-15 17:49
import os

from django.core.management import call_command
from django.db import migrations


def load_fixtures(apps, schema_editor):
    files = [
        'initial_data.json',
        'tipo_comprobantes.json',
        'alicuotas_iva.json',
        'condiciones_iva.json',
        'condiciones_venta.json',
        'unidades.json',
        'opcionales.json',
        'tipo_doc_otro.json',
        'tipo_docs.json',
        'tributos.json',
        'pais_destino.json',
        'monedas.json',
    ]
    fixtures_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
    for f in files:
        fixture_file = os.path.join(fixtures_dir, f)
        call_command('loaddata', fixture_file, app_label='afip')


class Migration(migrations.Migration):
    dependencies = [
        ('afip', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures)
    ]
