# Generated by Django 2.2.4 on 2019-08-14 21:07

import comprobante.models
import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('afip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lote_afip', models.IntegerField(null=True)),
                ('nro', models.IntegerField(null=True)),
                ('remito_nro', models.CharField(blank=True, default='', max_length=13, null=True)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_venc_pago', models.DateField(default=comprobante.models.venc_default)),
                ('cae', models.CharField(blank=True, max_length=256)),
                ('fecha_vto_cae', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=256)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
                ('reproceso', models.CharField(blank=True, max_length=256)),
                ('codigo_barras', models.ImageField(blank=True, null=True, upload_to='codigos_barras')),
                ('codigo_barras_nro', models.CharField(blank=True, max_length=256)),
                ('id_impositivo', models.CharField(blank=True, max_length=256, null=True)),
                ('moneda_ctz', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('observaciones_comerciales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('errores_wsfe', models.TextField(blank=True, null=True)),
                ('observaciones_wsfe', models.TextField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=256, null=True)),
                ('incoterms_ds', models.CharField(blank=True, max_length=256, null=True)),
                ('condicion_venta_texto', models.CharField(blank=True, max_length=256, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('cbte_asoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cliente')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.Concepto')),
                ('condicion_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.CondicionVenta')),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Idioma')),
                ('incoterms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Incoterms')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Moneda')),
            ],
        ),
        migrations.CreateModel(
            name='TributoComprobanteNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=256, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=4, max_digits=19)),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=19)),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.Tributo')),
            ],
        ),
        migrations.CreateModel(
            name='TributoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=256, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=4, max_digits=19)),
                ('alicuota', models.DecimalField(decimal_places=4, max_digits=19)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
                ('tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.Tributo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField(null=True)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_entrega_estimada', models.DateField(default=comprobante.models.venc_default)),
                ('fecha_entrega_limite', models.DateField(default=comprobante.models.venc_default)),
                ('gln_lugar_entrega', models.CharField(blank=True, max_length=128, null=True)),
                ('lugar_entrega', models.CharField(blank=True, max_length=256, null=True)),
                ('nro_proveedor_retail', models.CharField(max_length=128)),
                ('codigo_gln_retail', models.CharField(max_length=128)),
                ('codigo_gln_proveedor', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('INGR', 'Ingresada'), ('PEND', 'Pendiente'), ('VENC', 'Vencida'), ('CUMP', 'Cumplida')], default='INGR', max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Cliente')),
                ('tributo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobante.TributoComprobanteNA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcionalComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=256, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
                ('opcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.Opcional')),
            ],
        ),
        migrations.CreateModel(
            name='MailEnviadoComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('fecha_envio', models.DateTimeField(default=datetime.date.today)),
                ('estado', models.CharField(max_length=256)),
                ('texto', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=256)),
                ('precio_unit', models.DecimalField(decimal_places=4, max_digits=19)),
                ('codigo_proveedor_articulo', models.CharField(blank=True, max_length=128)),
                ('cantidad_cajas', models.IntegerField(blank=True, null=True)),
                ('unidades_x_caja', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('alicuota_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.AlicuotaIva')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante.OrdenCompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Producto')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Unidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, max_digits=19)),
                ('detalle', models.CharField(max_length=256)),
                ('precio_unit', models.DecimalField(decimal_places=4, max_digits=19)),
                ('alicuota_iva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.AlicuotaIva')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Producto')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Unidad')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comprobante.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='pais_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.PaisDestino'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='punto_vta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.PuntoDeVenta'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo_cbte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='afip.TipoComprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo_expo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.TipoExportacion'),
        ),
    ]
