# Generated by Django 2.2.9 on 2020-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0002_auto_20191114_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
