# Generated by Django 2.2.9 on 2020-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0003_comprobante_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='data_arreglada',
            field=models.BooleanField(default=False),
        ),
    ]
