# Generated by Django 2.2.4 on 2019-08-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_afip', models.IntegerField(verbose_name='Nro Punto de Venta')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=128)),
                ('nombre', models.CharField(max_length=256)),
                ('precio_unit', models.DecimalField(decimal_places=4, max_digits=19)),
                ('ingresa_precio_final', models.BooleanField(default=False)),
                ('codigo_barras_nro', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('alta_edi', models.BooleanField(default=False)),
                ('alicuota_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.AlicuotaIva')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('nro_doc', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=256, null=True)),
                ('localidad', models.CharField(blank=True, max_length=256, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=256, null=True)),
                ('nro_iibb', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_serv_desde', models.DateField(blank=True, null=True)),
                ('fecha_serv_hasta', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('mandar_copia_comprobante', models.BooleanField(default=True)),
                ('imprimir_comp_triplicado', models.BooleanField(default=False)),
                ('utiliza_edi', models.BooleanField(default=False)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.Concepto')),
                ('condicion_iibb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.CondicionIIBB')),
                ('condicion_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afip.CondicionIva')),
                ('resoluciones_generales', models.ManyToManyField(blank=True, to='afip.ResolucionGeneral')),
                ('tipos_cbte', models.ManyToManyField(to='afip.TipoComprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_doc', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=256)),
                ('domicilio', models.CharField(max_length=256)),
                ('localidad', models.CharField(max_length=256)),
                ('telefono', models.CharField(blank=True, max_length=256, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('agente_edi', models.BooleanField(default=False)),
                ('condicion_iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.CondicionIva')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afip.TipoDoc')),
            ],
        ),
    ]
