version: '2'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  redis:
    image: redis
    ports:
      - "6379:6379"
{% for group in groups %}
  pirra_{{group.container_number}}:
    build: .
    container_name: pirra_{{group.container_number}}
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL={{group.name}}.pirra.local
      - DJANGO_DATABASE={{group.name}}
      - DJANGO_DATABASE_USER={{group.name}}
      - DJANGO_DATABASE_PASSWORD={{"${" +group.env_var_name + "}"}}
    expose:
      - "8080"
    mem_limit: 300m
{% endfor %}