version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/src/pirra
#     - ./nginx/error.log:/etc/nginx/error_log.log
#     - ./nginx/cache/:/etc/nginx/cache
#     - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  # Tools
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  redis:
    image: redis
    ports:
      - "6379:6379"
{% for group in groups %}
  pirra_{{group.container_number}}:
    build: .
    container_name: pirra_{{group.container_number}}
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_SITE_URL={{group.name}}.pirra.local
      - DJANGO_DATABASE={{group.name}}
    expose:
      - "8080"
{% endfor %}
volumes:
  postgres-data:
    driver: local